/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("base")
    id("com.fussionlabs.gradle.go-plugin") version("0.5.2")
}

version = "1.0.0"

val operatorName = "configmap-replicator"
val imageRepository = "dm0275/configmap-replicator"

go {
    os = listOf("linux")
    arch = listOf("amd64")
}

tasks.register("dockerBuild") {
    dependsOn(tasks.getByPath("goBuildLinuxAmd64"))
    doLast {
        exec {
            commandLine("docker", "build", "-t", "$imageRepository:$version", projectDir)
        }
    }
}
