/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("base")
}

version = "1.0.0"

val operatorName = "configmap-replicator-operator"
val imageRepository = "dm0275/configmap-replicator-operator"

tasks.register("goBuild") {
    doLast {
        exec {
            environment("GOOS", "linux")
            environment("GOARCH", "amd64")
            environment("CGO_ENABLED", "0")
            mkdir(layout.buildDirectory.get())
            commandLine("go", "build", "-o", "${layout.buildDirectory.get()}/$operatorName", "$projectDir")
        }
    }
}

tasks.register("dockerBuild") {
    doLast {
        exec {
            commandLine("docker", "build", "-t", "$imageRepository:$version", projectDir)
        }
    }
}

tasks.getByName("build").dependsOn("goBuild")