/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("base")
}

tasks.register("goBuild") {
    doLast {
        exec {
            mkdir(layout.buildDirectory.get())
            commandLine("go", "build", "-o", "${layout.buildDirectory.get()}/configmap-replicator-operator", "$projectDir")
        }
    }
}

tasks.getByName("build").dependsOn("goBuild")