apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-replicator-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-replicator-controller
  template:
    metadata:
      labels:
        app: configmap-replicator-controller
    spec:
      serviceAccountName: configmap-replicator-controller-sa
      containers:
        - name: configmap-replicator-controller
          image: dm0275/configmap-replicator:1.0.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "1"